name: Build & Push (lemon)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write   # necesario para publicar a GHCR con GITHUB_TOKEN

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: Dev-Projects-planet/lemon

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (lemon:latest)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./containers/app/Dockerfile
          push: true
          tags: ghcr.io/lemon:latest
